version: 2
jobs:
  bundle_dependencies:
    working_directory: ~/redux-rn-misc-enhancer
    docker:
      - image: circleci/node:8.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - redux-rn-misc-enhancer-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - redux-rn-misc-enhancer-{{ arch }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "npm $(node -v)"
      - run:
          name: Install dependencies
          command: 'yarn install'
      - save_cache:
          key: redux-rn-misc-enhancer-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/redux-rn-misc-enhancer/node_modules

  compile_and_test:
    working_directory: ~/redux-rn-misc-enhancer
    docker:
      - image: circleci/node:8.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - redux-rn-misc-enhancer-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - redux-rn-misc-enhancer-{{ arch }}
      - run:
          name: Install dependencies
          command: 'yarn install'
      - run:
          name: Compile TypeScript
          command: 'yarn tsc'
      - run:
          name: Unit Test
          command: 'yarn test'

  deploy_to_npm:
    working_directory: ~/redux-rn-misc-enhancer
    docker:
      - image: circleci/node:8.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - redux-rn-misc-enhancer-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - redux-rn-misc-enhancer-{{ arch }}
      - run:
          name: Install dependencies
          command: 'yarn install'
      - run:
          name: Compile TypeScript
          command: 'yarn tsc'
      - run:
          name: Login to npm and publish
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm publish
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - bundle_dependencies:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - compile_and_test:
          requires:
            - bundle_dependencies
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy_to_npm:
          requires:
            - compile_and_test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/